search:
    image: elasticsearch
    ports:
     - "9200:9200"
     - "9300:9300"
    volumes:
     - /opt/dacc_search:/usr/share/elasticsearch/data
aristotle:
    build: .
    ports:
     - "5000"
    links:
     - search
web:
    build: .
    dockerfile: DockerNginx
    links:
     - aristotle:aristotle
    ports:
     - 80:80
     - 443:443
