search:
    image: elasticsearch
    ports:
     - "9200:9200"
     - "9300:9300"
    volumes:
     - /opt/dacc_search:/usr/share/elasticsearch/data
aristotle:
    build: .
    ports:
     - "7000:5000"
    links:
     - search

